---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scaling.gg.com
  resources:
  - timebasedscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.gg.com
  resources:
  - timebasedscalers/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.gg.com
  resources:
  - timebasedscalers/status
  verbs:
  - get
  - patch
  - update
