# permissions for end users to edit timebasedscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: timebasedscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeoperator-demo
    app.kubernetes.io/part-of: kubeoperator-demo
    app.kubernetes.io/managed-by: kustomize
  name: timebasedscaler-editor-role
rules:
- apiGroups:
  - scaling.gg.com
  resources:
  - timebasedscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.gg.com
  resources:
  - timebasedscalers/status
  verbs:
  - get
