apiVersion: scaling.gg.com/v1alpha1
kind: TimeBasedScaler
metadata:
  labels:
    app.kubernetes.io/name: timebasedscaler
    app.kubernetes.io/instance: timebasedscaler-sample
    app.kubernetes.io/part-of: kubeoperator-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeoperator-demo
  name: timebasedscaler-sample
spec:
  - name: demo
  - endHour: 16
  - startHour: 13
  - replicaCount: 2
  - deployments:
    - name: test
      namespace: default
